apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      labels:
        app: payments

    spec:
      imagePullSecrets:
      - name: jfrog-secret

      containers:
      - name: payments
        image: image_name
        ports:
        - containerPort: 3004
