apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products

    spec:
      imagePullSecrets:
      - name: jfrog-secret

      containers:
      - name: products
        image: image_name
        ports:
        - containerPort: 3002
