apiVersion: apps/v1
kind: Deployment
metadata:
  name: userss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users

  template:
    metadata:
      labels:
        app: users

    spec:
      imagePullSecrets:
      - name: jfrog-secret

      containers:
      - name: users
        image: image_name
        ports:
        - containerPort: 3001
